import { Empleados } from "@/app/domain/entities";
import { NextResponse } from "next/server";



export async function GET(request: Request) {


    const empleados : Empleados[] = [

        {
            "activo": "V",
            "empleado": 17,
            "nombre": "JESUS JAVIER",
            "materno": "GONZALEZ",
            "paterno": "GALAVIZ",
            "idPue": 34,
            "descripcionPuesto": "INTENDENTE",
            "deptoUe": 25,
            "deptoPpto": 25,
            "obra": 0,
            "descripcionDepto": "COORDINACION DE RECURSOS MATERIALES",
            "deptoComi": 25,
            "nombreCompleto": "JESUS JAVIER GALAVIZ GONZALEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 3,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 84,
            "nombre": "PEDRO",
            "materno": "AVILES",
            "paterno": "TAMAYO",
            "idPue": 52,
            "descripcionPuesto": "SUPERVISOR DE INSTALACIONES ELECTRICAS DE POTENCIA",
            "deptoUe": 18,
            "deptoPpto": 18,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO ELECTRICO",
            "deptoComi": 18,
            "nombreCompleto": "PEDRO TAMAYO AVILES",
            "municipio": 1,
            "oficina": 2,
            "nivel": 13,
            "lugarTrab": 2,
            "correo": "ptamayo@ceabc.gob.mx"
          },
          {
            "activo": "V",
            "empleado": 86,
            "nombre": "LEONEL OCTAVIO",
            "materno": "SANTOYO",
            "paterno": "AVILA",
            "idPue": 22,
            "descripcionPuesto": "ELECTRICISTA EN BAJA Y ALTA TENSION",
            "deptoUe": 18,
            "deptoPpto": 18,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO ELECTRICO",
            "deptoComi": 18,
            "nombreCompleto": "LEONEL OCTAVIO AVILA SANTOYO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 4,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 93,
            "nombre": "RAUL",
            "materno": "ROMERO",
            "paterno": "RAMIREZ",
            "idPue": 44,
            "descripcionPuesto": "OPERADOR DE MAQUINARIA DE MANTENIMIENTO DE OBRA CIVIL",
            "deptoUe": 20,
            "deptoPpto": 20,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "RAUL RAMIREZ ROMERO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 100,
            "nombre": "EFRAIN",
            "materno": "MONTOYA",
            "paterno": "CASTRO",
            "idPue": 44,
            "descripcionPuesto": "OPERADOR DE MAQUINARIA DE MANTENIMIENTO DE OBRA CIVIL",
            "deptoUe": 20,
            "deptoPpto": 20,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO DE OBRA CIVIL",
            "deptoComi": 20,
            "nombreCompleto": "EFRAIN CASTRO MONTOYA",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 109,
            "nombre": "ARTURO",
            "materno": "GARFIAS",
            "paterno": "ROMAN",
            "idPue": 35,
            "descripcionPuesto": "CUADRILLERO",
            "deptoUe": 20,
            "deptoPpto": 20,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO DE OBRA CIVIL",
            "deptoComi": 20,
            "nombreCompleto": "ARTURO ROMAN GARFIAS",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 117,
            "nombre": "JOSE JAIME",
            "materno": "BUSTAMANTE",
            "paterno": "MEZA",
            "idPue": 11,
            "descripcionPuesto": "CHOFER",
            "deptoUe": 12,
            "deptoPpto": 12,
            "obra": 0,
            "descripcionDepto": "DIRECCION DE OPERACION Y MANTENIMIENTO",
            "deptoComi": 12,
            "nombreCompleto": "JOSE JAIME MEZA BUSTAMANTE",
            "municipio": 1,
            "oficina": 2,
            "nivel": 3,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 123,
            "nombre": "ROBERTO",
            "materno": "GUERRERO",
            "paterno": "FIGUEROA",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ROBERTO FIGUEROA GUERRERO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 129,
            "nombre": "ISIDRO",
            "materno": "BELTRAN",
            "paterno": "FELIX",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ISIDRO FELIX BELTRAN",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 130,
            "nombre": "ENRIQUE",
            "materno": "BETANCOURT",
            "paterno": "AHUMADA",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ENRIQUE AHUMADA BETANCOURT",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 133,
            "nombre": "XAVIER",
            "materno": "Y CURIEL",
            "paterno": "CURIEL",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "XAVIER CURIEL Y CURIEL",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 134,
            "nombre": "ROBERTO",
            "materno": "LARA",
            "paterno": "CARO",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ROBERTO CARO LARA",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 135,
            "nombre": "MARCO ANTONIO",
            "materno": "VALENZUELA",
            "paterno": "VALDEZ",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "MARCO ANTONIO VALDEZ VALENZUELA",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 143,
            "nombre": "EFRAIN",
            "materno": "CAMACHO",
            "paterno": "VALDEZ",
            "idPue": 108,
            "descripcionPuesto": "COORDINADOR DE OPERACION",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "EFRAIN VALDEZ CAMACHO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 17,
            "lugarTrab": 2,
            "correo": "evaldez@ceabc.gob.mx"
          },
          {
            "activo": "V",
            "empleado": 145,
            "nombre": "ESTEBAN ALEJANDRO",
            "materno": "CASADO",
            "paterno": "VAZQUEZ",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ESTEBAN ALEJANDRO VAZQUEZ CASADO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 146,
            "nombre": "EZEQUIEL",
            "materno": "TIRADO",
            "paterno": "CASAREZ",
            "idPue": 79,
            "descripcionPuesto": "AUXILIAR DE ELECTRICISTA EN BAJA Y ALTA TENSION",
            "deptoUe": 18,
            "deptoPpto": 18,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO ELECTRICO",
            "deptoComi": 18,
            "nombreCompleto": "EZEQUIEL CASAREZ TIRADO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 4,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 148,
            "nombre": "MANUEL DE JESUS",
            "materno": "TIRADO",
            "paterno": "CAZARES",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "MANUEL DE JESUS CAZARES TIRADO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 149,
            "nombre": "JUAN ALBERTO",
            "materno": "MARIÑEZ",
            "paterno": "SALGADO",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "JUAN ALBERTO SALGADO MARIÑEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 150,
            "nombre": "JESUS",
            "materno": "TAMAYO",
            "paterno": "MARTINEZ",
            "idPue": 35,
            "descripcionPuesto": "CUADRILLERO",
            "deptoUe": 20,
            "deptoPpto": 20,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO DE OBRA CIVIL",
            "deptoComi": 20,
            "nombreCompleto": "JESUS MARTINEZ TAMAYO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 153,
            "nombre": "JOSE LUIS",
            "materno": "MADUEÑO",
            "paterno": "CAMPAÑA",
            "idPue": 22,
            "descripcionPuesto": "ELECTRICISTA EN BAJA Y ALTA TENSION",
            "deptoUe": 18,
            "deptoPpto": 18,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO ELECTRICO",
            "deptoComi": 18,
            "nombreCompleto": "JOSE LUIS CAMPAÑA MADUEÑO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 4,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 158,
            "nombre": "JOSE RODOLFO",
            "materno": "GERARDO",
            "paterno": "MARTINEZ",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "JOSE RODOLFO MARTINEZ GERARDO",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 161,
            "nombre": "JOSE LUIS",
            "materno": "GONZALEZ",
            "paterno": "PARRA",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "JOSE LUIS PARRA GONZALEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 162,
            "nombre": "CARLOS ENRIQUE",
            "materno": "LOPEZ",
            "paterno": "GONZALEZ",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "CARLOS ENRIQUE GONZALEZ LOPEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 164,
            "nombre": "ISMAEL",
            "materno": "LOPEZ",
            "paterno": "ANGULO",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "ISMAEL ANGULO LOPEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 167,
            "nombre": "HUGO",
            "materno": "RAMIREZ",
            "paterno": "HIGUERA",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "HUGO HIGUERA RAMIREZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 171,
            "nombre": "MIGUEL ANTONIO",
            "materno": "GUTIERREZ",
            "paterno": "DELGADO",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "MIGUEL ANTONIO DELGADO GUTIERREZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 175,
            "nombre": "FRANCISCO JAVIER",
            "materno": "CARBAJAL",
            "paterno": "ROA",
            "idPue": 43,
            "descripcionPuesto": "OPERADOR DE PLANTA DE BOMBEO",
            "deptoUe": 15,
            "deptoPpto": 15,
            "obra": 0,
            "descripcionDepto": "COORD. DE OPERACION",
            "deptoComi": 15,
            "nombreCompleto": "FRANCISCO JAVIER ROA CARBAJAL",
            "municipio": 1,
            "oficina": 2,
            "nivel": 5,
            "lugarTrab": 2,
            "correo": "0"
          },
          {
            "activo": "V",
            "empleado": 178,
            "nombre": "HECTOR JESUS",
            "materno": "LOPEZ",
            "paterno": "CASTILLO",
            "idPue": 22,
            "descripcionPuesto": "ELECTRICISTA EN BAJA Y ALTA TENSION",
            "deptoUe": 18,
            "deptoPpto": 18,
            "obra": 0,
            "descripcionDepto": "COORD. DE MANTENIMIENTO ELECTRICO",
            "deptoComi": 18,
            "nombreCompleto": "HECTOR JESUS CASTILLO LOPEZ",
            "municipio": 1,
            "oficina": 2,
            "nivel": 4,
            "lugarTrab": 2,
            "correo": "0"
          },
        ]

    return NextResponse.json({ 
        data: empleados,
    } );

}